on:
  push:
    branches:
      - dev
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Install AWS CDK
        run: |
            npm install -g aws-cdk
          
      - name: Restore .NET dependencies
        run: |
            cd src
            dotnet restore ./LambdaAttempt.sln
          
      - name: Build project
        run: |
            dotnet build 
          
      - name: Synthesize CDK
        run: |
            cdk synth
          
      - name: Deploy CDK stack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'sa-east-1'
        run: |
            cdk deploy --require-approval never