on:
  push:
    branches:
      - dev
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    setps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Install AWS CDK
        run: |
            npm install -g aws-cdk
          
      - name: Restore .NET dependencies
        run: |
            dotnet restore
          
      - name: Deploy CDK
        uses: P47Phoenix/dotnet-cdk-action@v1
        with:
          cdk_command: deploy
          cdk_args: --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}